const ConnectKitTheme = {
    "--ck-font-family": "Inter",
    "--ck-font-weight": "400",
    "--ck-border-radius": "20px",
    "--ck-overlay-backdrop-filter": "blur(2px)",
    "--ck-modal-heading-font-weight": "700",
    "--ck-qr-border-radius": "16px",
    "--ck-connectbutton-font-size": "15px",
    "--ck-connectbutton-color": "#373737",
    "--ck-connectbutton-background": "#d9e2fd",
    "--ck-connectbutton-background-secondary": "#FFFFFF",
    "--ck-connectbutton-border-radius": "16px",
    "--ck-connectbutton-box-shadow": "2px 2px 3px 2px #5b9ddf",
    "--ck-connectbutton-hover-color": "#00253b",
    "--ck-connectbutton-hover-background": "#c1d1fe",
    "--ck-connectbutton-hover-box-shadow": "2px 2px 3px 2px #5b9ddf",
    "--ck-connectbutton-active-color": "#3d4b53",
    "--ck-connectbutton-active-background": "#dfe7ff",
    "--ck-connectbutton-active-box-shadow": "0 0 0 0 #ffffff",
    "--ck-connectbutton-balance-color": "#373737",
    "--ck-connectbutton-balance-background": "#fff",
    "--ck-connectbutton-balance-box-shadow": "inset 0 0 0 1px #F6F7F9",
    "--ck-connectbutton-balance-hover-background": "#F6F7F9",
    "--ck-connectbutton-balance-hover-box-shadow": "inset 0 0 0 1px #F0F2F5",
    "--ck-connectbutton-balance-active-background": "#F0F2F5",
    "--ck-connectbutton-balance-active-box-shadow": "inset 0 0 0 1px #EAECF1",
    "--ck-primary-button-font-weight": "500",
    "--ck-primary-button-border-radius": "16px",
    "--ck-primary-button-color": "#000000",
    "--ck-primary-button-background": "#a1baff",
    "--ck-primary-button-box-shadow": "2px 2px 12px 0px #5ea6ed",
    "--ck-primary-button-hover-color": "#00253b",
    "--ck-primary-button-hover-background": "#c1d1fe",
    "--ck-primary-button-hover-box-shadow": "3px 5px 11px 0px #5b9ddf",
    "--ck-primary-button-active-color": "#373737",
    "--ck-primary-button-active-background": "#d9e2fd",
    "--ck-primary-button-active-box-shadow": "0px 0px 0px 0px #5b9ddf",
    "--ck-secondary-button-font-weight": "500",
    "--ck-secondary-button-border-radius": "16px",
    "--ck-secondary-button-color": "#000000",
    "--ck-secondary-button-background": "#a1baff",
    "--ck-secondary-button-box-shadow": "2px 2px 12px 0px #5ea6ed",
    "--ck-secondary-button-hover-color": "#00253b",
    "--ck-secondary-button-hover-background": "#c1d1fe",
    "--ck-secondary-button-hover-box-shadow": "3px 5px 11px 0px #5b9ddf",
    "--ck-secondary-button-active-color": "#373737",
    "--ck-secondary-button-active-background": "#ffffff",
    "--ck-secondary-button-active-box-shadow": "0px 0px 0px 0px #ffffff",
    "--ck-tertiary-button-font-weight": "500",
    "--ck-tertiary-button-border-radius": "16px",
    "--ck-tertiary-button-color": "#000000",
    "--ck-tertiary-button-background": "#a1baff",
    "--ck-tertiary-button-box-shadow": "2px 2px 11px 0px #ffffff",
    "--ck-tertiary-button-hover-color": "#00253b",
    "--ck-tertiary-button-hover-background": "#c1d1fe",
    "--ck-tertiary-button-hover-box-shadow": "3px 5px 11px 0px #5b9ddf",
    "--ck-tertiary-button-active-color": "#373737",
    "--ck-tertiary-button-active-background": "#F6F7F9",
    "--ck-tertiary-button-active-box-shadow": "0 0 0 0 #ffffff",
    "--ck-modal-box-shadow": "0px 2px 4px 0px #00000005",
    "--ck-overlay-background": "#4f7eff2e",
    "--ck-body-color": "#000000",
    "--ck-body-color-muted": "#000000",
    "--ck-body-color-muted-hover": "#003a6c",
    "--ck-body-background": "#a1baff",
    "--ck-body-background-transparent": "rgba(255,255,255,0)",
    "--ck-body-background-secondary": "#dfe7ff",
    "--ck-body-background-secondary-hover-background": "#e0e4eb",
    "--ck-body-background-secondary-hover-outline": "#4282FF",
    "--ck-body-background-tertiary": "#dfe7ff",
    "--ck-body-action-color": "#000000",
    "--ck-body-divider": "#ffffff",
    "--ck-body-color-danger": "#ff5050",
    "--ck-body-color-valid": "#3aff58",
    "--ck-siwe-border": "#F0F0F0",
    "--ck-body-disclaimer-background": "#f6f7f9",
    "--ck-body-disclaimer-color": "#AAAAAB",
    "--ck-body-disclaimer-link-color": "#838485",
    "--ck-body-disclaimer-link-hover-color": "#000000",
    "--ck-tooltip-background": "#a1baff",
    "--ck-tooltip-background-secondary": "#dfe7ff",
    "--ck-tooltip-color": "#000000",
    "--ck-tooltip-shadow": "0px 2px 4px 0px #3f577cbd",
    "--ck-dropdown-button-color": "#999999",
    "--ck-dropdown-button-box-shadow": "0 0 0 1px rgba(0,0,0,0.01), 0px 0px 7px rgba(0, 0, 0, 0.05)",
    "--ck-dropdown-button-background": "#fff",
    "--ck-dropdown-button-hover-color": "#8B8B8B",
    "--ck-dropdown-button-hover-background": "#F5F7F9",
    "--ck-qr-dot-color": "#000000",
    "--ck-qr-background": "#dfe7ff",
    "--ck-qr-border-color": "#ffffff",
    "--ck-focus-color": "#1A88F8",
    "--ck-spinner-color": "#1188ff",
    "--ck-copytoclipboard-stroke": "#CCCCCC",
    "--ck-recent-badge-color": "#5e5e5e",
    "--ck-recent-badge-background": "#a1baff",
    "--ck-recent-badge-border-radius": "32px"
  }

export default ConnectKitTheme;